apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  ports:
  - port: 80
    name: webapp
  clusterIP: None
  selector:
    app: tomcat
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webapp
spec:
  serviceName: "tomcat"
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: gcr.io/potent-pursuit-310906/ubuntu_tomcat
        ports:
        - containerPort: 80
          name: webapp
